services:
  - type: web
    name: jimmymuthoni-portfolio
    runtime: go
    plan: free
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
